name: React CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      # Use a full install with legacy-peer-deps to ensure everything works
      run: npm install --legacy-peer-deps
      
    - name: Run linting
      run: npm run lint || echo "No linting configured"
    
    - name: Run tests with verbosity for debugging
      # Use --no-watchman to avoid watchman issues
      run: npm test -- --passWithNoTests --no-watchman --verbose
    
    - name: Build
      run: npm run build